channels:
- conda-forge
dependencies:
- python=3.11.11
- pip<=24.1.2
- pip:
  - mlflow==2.19.0
  - cffi==1.17.1
  - cloudpickle==3.1.1
  - cupy-cuda12x==13.3.0
  - defusedxml==0.7.1
  - graphviz==0.20.3
  - jinja2==3.1.5
  - lightgbm==4.5.0
  - matplotlib==3.10.0
  - numpy==1.26.4
  - nvidia-ml-py==12.570.86
  - optuna==4.4.0
  - pandas==2.2.2
  - pathlib==1.0.1
  - pyarrow==18.1.0
  - pytest==8.3.5
  - python-snappy==0.7.3
  - rapids-dask-dependency==25.2.0
  - rmm-cu12==25.2.0
  - scikit-learn==1.6.1
  - scipy==1.13.1
  - setproctitle==1.3.5
  - zstandard==0.23.0
name: mlflow-env
